### ISSUE TITLE
Encoding issue 

### ISSUE THREAD

**Issue by BuckinghamIO** [paymentwall/paymentwall-python#14]
Using version 1.0.6 with Python 3.5 results in a exception when hasing params here:

	@classmethod
	def hash(cls, string, library_type):
		hashed_string = hashlib.md5() if library_type == 'md5' else hashlib.sha256()
		hashed_string.update(string)
		return hashed_string.hexdigest()

If you add .encode('utf-8') to string it seems to fix the issue however I still end up with error trying to load the widget url:

```https://api.paymentwall.com/api/subscription?sign=825b6e2b214c3d04fbed260ad2e357f599c5c67275a803c7516e1ef2aec4f0e6&key=5308f2cbea5a4526a1c0f8a8b3019ac0&sign_version=3&ag_external_id=12448504&ag_type=fixed&uid=xXxKillDogxXx&widget=p1_1&amount=20.00&ag_name=Example+Server+Store+Purchase&currencyCode=USD```

Error is: The request signature is wrong or expired

Any help on where I can start to debug this issue? 

```It looks like you're not authorized to view this content. The request signature is wrong or expired (sign=825b6e2b214c3d04fbed260ad2e357f599c5c67275a803c7516e1ef2aec4f0e6).```

**Comment by BuckinghamIO** [comment]
Found the issue:

```    
def get_name(self):
        if self.name:
            return self.name.encode('utf-8')
        return None
```

removing the encode from the above function and instead forcing the encode here:

```
    @classmethod
    def hash(cls, string, library_type):
        hashed_string = hashlib.md5() if library_type == 'md5' else hashlib.sha256()
        hashed_string.update(string.encode('utf-8'))
        return hashed_string.hexdigest()
```

This resolves the problem completely, I believe the issue lies in the calculate signature function where it orders and sorts the parameters. I think when handling a byte string the result is different.

**Comment by BuckinghamIO** [comment]
Let me know if you want me to make a PR

**Comment by hdolinski** [comment]
Hi Sam,

thanks for the help! Issue fixed in version 1.0.7

**Comment by BuckinghamIO** [comment]
@hdolinski Thanks for the quick response, I was going to include it in my PR. Either way I'll send over a PR now with some Django framework examples :)

**Comment by wansheg** [comment]
it is clear that hashlib.hashalgorith.update( ... ) only handle "bytes",  you cause regression . 
     - update(arg): Update the hash object with the bytes in arg. Repeated calls
                    are equivalent to a single call with the concatenation of all

the fix is wrong completely !!!
