### ISSUE TITLE
__init__.py missing since v1.0.7

### ISSUE THREAD

**Issue by BuckinghamIO** [paymentwall/paymentwall-python#16]
Any particular reason for this, it was quite helpful and I also believe this makes some of the examples incorrect?

It breaks:

from paymentwall import * 

I would now have to do:

from paymentwall.base import Paymentwall

Unless there is a reason/benefit I'm not seeing?

**Comment by LiangNex** [comment]
The __init__.py is added back.  Thanks for pointing it out.
