### ISSUE TITLE
hashlib hash algorithm accept  bytes in python3 , the code is obsolted for python3

### ISSUE THREAD

**Issue by wansheg** [paymentwall/paymentwall-python#23]
@classmethod
        def hash(cls, string, library_type):
                hashed_string = hashlib.md5() if library_type == 'md5' else hashlib.sha256()
                hashed_string.update(string.encode('utf-8')) // here is wrong !!!!
                return hashed_string.hexdigest()

**Comment by ArtemiusUA** [comment]
@wansheg 
Seems this issue was fixed in the commit: https://github.com/paymentwall/paymentwall-python/commit/05aa7657108884892208b69e67869cbd93272f93

**Comment by everping** [comment]
I have also found that when using paymentwall-python 1.0.7 from Pypi repository. The last version in Github was fixed it but not updated in the Pypi.

**Comment by ivan-kovalyov** [comment]
PyPI has been updated. Please feel free to update.
