### ISSUE TITLE
I have installed paymentwall-python the latest version 1.0.7, but not support python3

### ISSUE THREAD

**Issue by SpeedMe** [paymentwall/paymentwall-python#24]
I saw the issue #23 . But the latest version 1.0.7 pip install  still self.hash(base_string.encode('utf-8'), 'sha256').

**Comment by evilplanet** [comment]
I'm not sure if this is related, but I have installed version 1.0.7 with python3 as well. And I can't import anything from paymentwall.

**Comment by ivan-kovalyov** [comment]
PyPI has been updated. Please feel free to update.
