### ISSUE TITLE
ImportError with paymentwall-python 1.0.7 and Python 3.5.4

### ISSUE THREAD

**Issue by evilplanet** [paymentwall/paymentwall-python#25]
```
from paymentwall import *
Paymentwall.set_api_type(Paymentwall.API_GOODS)
......
```
Following the documentation testing the API, it throws the below error:
```
Traceback (most recent call last):
  File "/Users/username/project/app/paymentwall.py", line 1, in <module>
    from paymentwall import *
  File "/Users/username/project/app/paymentwall.py", line 4, in <module>
    Paymentwall.set_api_type(Paymentwall.API_GOODS)
NameError: name 'Paymentwall' is not defined
```

I've also tried `from paymentwall import Paymentwall` but to no avail.
I have `paymentwall-python 1.0.7` and `Python 3.5.4` in the same `conda` virtual environment.

**Comment by evilplanet** [comment]
Hello?

**Comment by michaelpw** [comment]
Hi,

I've just tested with Python 3.5.4

Please install the SDK following the instruction below:

1. Add the file __init__.py to folder **paymentwall**
2. Run command **python setup.py install**

Then try to import, it should work fine

I will add back the file __init__.py

**Comment by evilplanet** [comment]
@michaelpw  Thank you for the reply. Will the `pypi` version be fixed as well? I need to use it on Heroku. It's easier to run `pip install`.

**Comment by ivlevdenis** [comment]
@evilplanet install from this git repo
