### ISSUE TITLE
Update the newest version to Pypi repository

### ISSUE THREAD

**Issue by everping** [paymentwall/paymentwall-python#27]
The current version in Pypi repository (1.0.7) is not the latest version. Please update it as soon as possible.

That version is the main reason making applications cannot work (https://github.com/paymentwall/paymentwall-python/issues/23, https://github.com/paymentwall/paymentwall-python/issues/24)

**Comment by ivan-kovalyov** [comment]
PyPI has been updated. Please feel free to update.
