### ISSUE TITLE
IP Whitelisting does not allow the latest ip addition

### ISSUE THREAD

**Issue by sharmi** [paymentwall/paymentwall-python#29]
As documented in [PaymentWall : Pingback New IP Subnet - November 2018](https://docs.paymentwall.com/reference/pingback-new-ip-subnet)

They also request to remove the existing IPs from the list after migrating to the new IP Subnet

**Comment by ivan-kovalyov** [comment]
This has been solved in the latest version.

**Comment by ivan-kovalyov** [comment]
Please see https://github.com/paymentwall/paymentwall-python/commit/81c9e4474e15e4d4c212126b3ae428a3b5c4533a
